project:
  type: website
  output-dir: docs

website:
  title: "BDD26"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - resources.qmd
      - help.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

