---
title: "Resources"
---

```{r, include = FALSE}
library(dplyr)
library(kableExtra)
```

## Videos

Check out my [Intro to R Youtube Channel](https://www.youtube.com/@IntroductionToR/playlists)! These feature lessons from courses I teach through National Institutes of Health and Johns Hopkins University.

## Getting started

- [R reference card](http://cran.r-project.org/doc/contrib/Short-refcard.pdf)
- [R introductory guide](https://cran.r-project.org/doc/manuals/r-release/R-intro.html)
- [R jargon](https://link.springer.com/content/pdf/bbm%3A978-1-4419-1318-0%2F1.pdf)
- [R terminology](https://cran.r-project.org/doc/manuals/r-release/R-lang.pdf)
- [What is the Tidyverse/what packages are in it?](https://www.tidyverse.org/packages/)
- [Where do package names come from?](https://www.statworx.com/en/content-hub/blog/why-is-it-called-that-way-origin-and-meaning-of-r-package-names/)
- [Lawlor et al. 2022](https://doi.org/10.1371/journal.pcbi.1010372): Ten simple rules for teaching yourself R

## Troubleshooting guides

- [Guide on when to use quotes or backticks](https://jhudatascience.org/intro_to_r/resources/quotes_vs_backticks.html)
- [Guide on what functions require `pull()` first](https://jhudatascience.org/intro_to_r/resources/functions_for_vectors.html)

## Keyboard shortcuts

- RStudio shortcuts can be found [here](http://www.rstudio.com/ide/docs/using/keyboard_shortcuts).

## Extra help

### Data importing

- [Video on data import](https://youtu.be/LEkNfJgpunQ)
- [Video](https://www.youtube.com/watch?v=we6vwB7DsNU) for PC users who want to see how to move files around (especially from downloads)
- [Video](https://www.youtube.com/watch?v=Ao9e0cDzMrE) for Mac users who want to see how to move files around (especially from downloads)
- [Extra information about file paths](https://docs.google.com/presentation/d/18u1Vhd3Uq-QprC0btpxS_-Ka-LKVUvncyoqdbGdb-g4/edit?usp=sharing)

### Joining datasets

- [`full-join()` animation](https://github.com/gadenbuie/tidyexplain/blob/master/images/full-join.gif)
- [`inner_join()` animation](https://github.com/gadenbuie/tidyexplain/blob/master/images/inner-join.gif)
- [`left-join()` animation](https://github.com/gadenbuie/tidyexplain/blob/master/images/left-join.gif)
- [`right-join()` animation](https://github.com/gadenbuie/tidyexplain/blob/master/images/right-join.gif)

### Plotting data

- [`ggplot2` gallery](https://r-graph-gallery.com/ggplot2-package.html) - See what is possible with `ggplot2` to create graphs in R
- [`ggplot2` theme cheatsheet](https://github.com/claragranell/ggplot2/blob/main/ggplot_theme_system_cheatsheet.pdf)
- [Visualization best practices](https://jhudatascience.org/tidyversecourse/dataviz.html#making-good-plots)
- [Guide on when to use which plot](https://infogram.com/page/choose-the-right-chart-data-visualization)
- [Guide to building up a `ggplot2` figure](https://hopstat.wordpress.com/2016/02/18/how-i-build-up-a-ggplot2-figure/)

### Statistics

- [Guide on when to use what stats test](https://www.scribbr.com/statistics/statistical-tests/)
- [Modeling 101](https://jhudatascience.org/tidyversecourse/model.html#linear-modeling)
- [Common statistical tests are linear models](https://lindeloev.github.io/tests-as-linear/) (why understanding linear models will get you far!)
- [Interpreting GLM output (e.g., deviance)](https://www.statology.org/null-residual-deviance/)

## Courses & Conferences

### Online Courses and Resources

- [Tidyverse Skills for Data Science Book](https://jhudatascience.org/tidyversecourse/) (**a great next step** to learn more about the tidyverse, some modeling, and machine learning)
- [Tidyverse Skills for Data Science Course](https://www.coursera.org/specializations/tidyverse-data-science-r) (same content with quizzes, can get certificate with \$)
- [Open Case Studies](https://www.opencasestudies.org/)\
  (resource for specific public health cases with statistical implementation and interpretation - **a great next step** for learning more about stats and wrangling!)
- [R for Data Science](http://r4ds.had.co.nz/) (great general information)
- [R for Applied Epidemiology](https://epirhandbook.com/en/) (Similar general introductory course)\
- [R basics chapter of Introduction to Data Science by Rafael A. Irizarry](https://rafalab.github.io/dsbook/r-basics.html)(great general information)
- [Dataquest](https://www.dataquest.io/) (general interactive resource)
- [Quick R Guide](http://statmethods.net/) (nice free general resource)
- [Introduction to Reproducibility](https://jhudatascience.org/Reproducibility_in_Cancer_Informatics/)
- [Advanced Reproducibility](https://jhudatascience.org/Adv_Reproducibility_in_Cancer_Informatics/)

### R Conferences

- The [RStudio/Posit conference](https://posit.co/conference/) has lots of useful workshops!
- useR! — International R User Conference information can be found [here](https://www.r-project.org/conferences/).

## R for Stata, SPSS, and SAS files

- The [Haven](https://haven.tidyverse.org/) package\
  (This package is super useful for reading and writing files so that they are compatible across Stata, SPSS, SAS, and R)
- [R vs Stata](https://link.springer.com/content/pdf/bbm%3A978-1-4419-1318-0%2F1.pdf)\
  (See page 505)
- [R \<-\> SAS Cheatsheet](https://raw.githubusercontent.com/rstudio/cheatsheets/main/sas-r.pdf)
- [SAS to R Converter](https://www.codeconvert.ai/sas-to-r-converter)\
- You might also find large language models like ChatGPT useful for code conversion. Be sure to check the output because AI makes mistakes!

